import Sidebar from '@/components/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'

const notoSansKr = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  display: 'swap',
  fallback: [
    'sans-serif'
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="[color-scheme:dark]">
      <body className={`flex flex-col-reverse sm:flex-row h-screen overflow-y-scroll ${notoSansKr.className}`}>
        <Sidebar />
        <main className='w-full h-full bg-neutral-900'>
          {children}
        </main>
      </body>
    </html>
  )
}
