import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import Topbar from '@/components/Topbar'
import Bottombar from '@/components/Bottombar'

const notoSansKr = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  display: 'swap',
  fallback: [
    'helvetica', 'sans-serif'
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="[color-scheme:dark]">
      <body className={`flex flex-col ${notoSansKr.className}`}>
        <Topbar />
        <main className='w-full h-full'>
          {children}
        </main>
        <Bottombar />
      </body>
    </html>
  )
}
